name: Google Drive Authentication

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  authenticate-drive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade pydrive2 oauth2client

      - name: Debug Secret Value
        run: |
          if [ -z "${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}" ]; then
            echo "❌ ERROR: GDRIVE_SERVICE_ACCOUNT_JSON is missing or empty!"
            exit 1
          else
            echo "✅ GDRIVE_SERVICE_ACCOUNT_JSON is set."
          fi

      - name: Run authentication script
        env:
          GDRIVE_SERVICE_ACCOUNT_JSON: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}
        run: python drive_auth.py
